---
title: "Bike Rentals in D.C."
author: "Sebastian Kaltenbach"
date: "2021-10-31"
output: html_notebook
---
## Packages

Load the packages we need for this tutorial using the chunk below.

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)
library(dsbox)
library(lubridate)
library(janitor)
```

Analysis of the bikesharing data in September 2021

```{r}
df1 <- read_csv("202109-capitalbikeshare-tripdata.csv") %>% clean_names()
```

```{r}
df2 <- df1 %>% filter(mday(started_at) == 1)
```

```{r}
df3 <- df2 %>% mutate(hr = hour(started_at), dur = ended_at - started_at)
```

## Computing ridership vs. time

```{r}
df4 <- df1 %>% select(rideable_type, start = started_at, end = ended_at) %>%
  pivot_longer(cols = start:end, names_to = "type", values_to = "time") %>%
  arrange(time) %>%
  mutate(inc = case_when(
    type == "start" ~ 1,
    type == "end" ~ -1
  ),
  riders = cumsum(inc))
```

Can we plot over the entire month.

```{r}
df4 %>% mutate(day = mday(time), 
               day_label = wday(time, label = TRUE), 
               time_mod = (hour(time) * 60 + minute(time)) / 60) %>%
  ggplot(aes(time_mod, riders)) +
  geom_point(size = .5, alpha = .02) +
  facet_wrap(~ day, ncol = 7) +
  labs(titel = "Distribution of Bike sharing in D.C.", 
       subtitle = "Analysis: September 2021",
       x = "Hours of day [h]",
       y = "Amount of riders [-]")
```
ToDo:

improve on faceting to get a nicer plot for each daily profile
